trigger:
- main

pool:
  name: default

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  displayName: 'Restore projects'
  inputs:
    command: 'restore'
    projects: '$(solution)'
    feedsToUse: 'select'


- task: SonarCloudPrepare@2
  inputs:
    SonarCloud: 'Sonar'
    organization: 'farmerofb'
    scannerMode: MSBuild
    ProjectKey: 'farmerofb_PlanetWeight'
    ProjectName: 'PlanetWeight'
    extraProperties: |
      sonar.exclusions=**/obj/**,**/*.dll,**/*.csproj,**/*.sln,**/*.cshtml
      sonar.cs.opencover.reportsPaths=$(Build.SourcesDirectory)/PersistedTestResults/coverage.opencover.xml

- task: DotNetCoreCLI@2
  displayName: 'Build Solution'
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Run unit/bdd tests with coverage'
  inputs:
    command: 'test'
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration) --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover --results-directory $(Build.SourcesDirectory)/TestResults'

- script: |
    mkdir -p $(Build.SourcesDirectory)/PersistedTestResults
    cp $(Build.SourcesDirectory)/TestResults/coverage.opencover.xml $(Build.SourcesDirectory)/PersistedTestResults/
  displayName: 'Copy Coverage File to Persistent Directory'

- task: SonarCloudAnalyze@2
  displayName: 'Run sonar analysis'

- task: SonarCloudPublish@2
  displayName: 'Publish sonar result to Sonar Cloud'
  inputs:
    pollingTimeoutSec: '300'

  
- task: DotNetCoreCLI@2
  displayName: 'Publish Build Artifacts 1'
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output $(build.artifactStagingDirectory)'
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts 2'
  inputs:
    pathToPublish: '$(build.artifactStagingDirectory)'
    artifactName: 'drop'
    publishLocation: 'Container'
