trigger:
- main

pool:
  name: default

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'my-project.sln'
    feedsToUse: 'select'


- task: SonarCloudPrepare@2
  inputs:
    SonarCloud: 'Sonar'
    organization: 'farmerofb'
    scannerMode: CLI
    cliVersion: '6.1.0.4477'
    configMode: 'file'
    projectKey: 'farmerofb_PlanetWeight'
    projectName: 'PlanetWeight'
    cliProjectKey: 'farmerofb_PlanetWeight'
    cliProjectName: 'PlanetWeight'
    configFile: 'sonar-project.properties'

- task: DotNetCoreCLI@2
  displayName: 'Build Solution'
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Run unit/bdd tests with coverage'
  inputs:
    command: 'test'
    projects: '$(solution)'
    arguments: '--collect "Code Coverage"'


- task: SonarCloudAnalyze@2

- task: SonarCloudPublish@2
  inputs:
    pollingTimeoutSec: '300'

- task: DotNetCoreCLI@2
  displayName: 'Publish Build Artifacts'
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output $(build.artifactStagingDirectory)'
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(build.artifactStagingDirectory)'
    artifactName: 'drop'
    publishLocation: 'Container'
